version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: chat-app-postgres
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  chat-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app-server
    environment:
      NODE_ENV: development
      PORT: 3006
      FRONTEND_URL: http://localhost:3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: chat_app
      JWT_SECRET: your-secret-key
      JWT_EXPIRES_IN: 7d
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:3006/api/auth/google/callback
    ports:
      - "3006:3006"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3006/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
